spring:
  application:
    name: smart-meter-gateway
  datasource:
    url: jdbc:h2:file:~/smartMeterGateway/db;AUTO_SERVER=TRUE;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.enable_lazy_load_no_trans: true
  web:
    security:
      debug: false
  servlet:
    multipart:
      enabled: false # Blockiert Upload von Dateien
logging:
  level:
    org.springframework.security: INFO
server:
  port: 443
  error:
    include-stacktrace: never # CIS Benchmark Hardening Kapitel 2.5: Verhindert das Ausgeben von Stacktraces im Response Body
  ssl:
    enabled: true # CIS Benchmark Hardening Kapitel 6.2: Aktiviert TLS
    enabled-protocols: +TLSv1.2,+TLSv1.3
    key-store: classpath:keystore.p12
#    key-store-password: # via security.properties gesetzt
    key-store-type: PKCS12
    key-alias: smart-meter-gateway
    # Ciphers aus der TR-02102-2 des BSI, Kapitel 3.3.1.1
    ciphers: "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_CCM,TLS_ECDHE_ECDSA_WITH_AES_256_CCM,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_DSS_WITH_AES_128_CBC_SHA256,TLS_DHE_DSS_WITH_AES_256_CBC_SHA256,TLS_DHE_DSS_WITH_AES_128_GCM_SHA256,TLS_DHE_DSS_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_128_CBC_SHA256,TLS_DHE_RSA_WITH_AES_256_CBC_SHA256,TLS_DHE_RSA_WITH_AES_128_GCM_SHA256,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_128_CCM,TLS_DHE_RSA_WITH_AES_256_CCM"
  tomcat:
    connection-timeout: 10s # CIS Benchmark Hardening Kapitel 10.9: Verhindert DoS-Angriffe
    max-http-response-header-size: 8KB # CIS Benchmark Hardening Kapitel 10.10: Verhindert DoS-Angriffe
    accesslog:
      enabled: true
      directory: logs # Logging von HTTP-Zugriffen auf Endpoints der Smart Meter Gateway Applikation
    basedir: tomcat
  max-http-request-header-size: 8KB # CIS Benchmark Hardening Kapitel 10.10: Verhindert DoS-Angriffe
  server-header: ~ # CIS Benchmark Hardening Kapitel 2.1 - 2.3; 2.7: Verhindert das Ausgeben von Serverinformationen
management:
  endpoints:
    web:
      exposure:
        include: "health" # ermöglicht lediglich den Zugriff auf den Health-Endpoint
smartmeter:
  operator:
    username: operator
#    password: via security.properties gesetzt
