spring:
  application:
    name: smart-meter-gateway
  datasource:
    url: jdbc:h2:file:~/smartMeterGateway/db;AUTO_SERVER=TRUE;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  web:
    security:
      debug: false
logging:
  level:
    org.springframework.security: INFO